accounts/avatar/urls.py
from django.conf.urls.defaults import patterns, url

from .views import add, change, delete



urlpatterns = patterns ('accounts.avatar.views',
    url (r'^add/$', 
         add, 
         {'template_name': 'accounts/avatar/change.html',},
         name='avatar_add'),
    url (r'^change/$', 
         change,
         {'template_name': 'accounts/avatar/change.html',},
         name='avatar_change'),
    url (r'^delete/$', 
         delete,
         {'template_name': 'accounts/avatar/delete.html',},
         name='avatar_delete'),
    url('^render_primary/(?P<user>[\+\w]+)/(?P<size>[\d]+)/$', 'render_primary', name='avatar_render_primary'),    
)

actstream/urls.py
from django.conf.urls.defaults import *
from actstream import feeds

urlpatterns = patterns('actstream.views',
    # Syndication Feeds
    url(r'^feed/(?P<content_type_id>\d+)/(?P<object_id>\d+)/atom/$',
        feeds.AtomObjectActivityFeed(), name='actstream_object_feed_atom'),
    url(r'^feed/(?P<content_type_id>\d+)/(?P<object_id>\d+)/$',
        feeds.ObjectActivityFeed(), name='actstream_object_feed'),
    url(r'^feed/(?P<content_type_id>\d+)/atom/$',
        feeds.AtomModelActivityFeed(), name='actstream_model_feed_atom'),
    url(r'^feed/(?P<content_type_id>\d+)/(?P<object_id>\d+)/as/$',
        feeds.ActivityStreamsObjectActivityFeed(),
        name='actstream_object_feed_as'),
    url(r'^feed/(?P<content_type_id>\d+)/$',
        feeds.ModelActivityFeed(), name='actstream_model_feed'),
    url(r'^feed/$', feeds.UserActivityFeed(), name='actstream_feed'),
    url(r'^feed/atom/$', feeds.AtomUserActivityFeed(),
        name='actstream_feed_atom'),

    # Follow/Unfollow API
    url(r'^follow/(?P<content_type_id>\d+)/(?P<object_id>\d+)/$',
        'follow_unfollow', name='actstream_follow'),
    url(r'^unfollow/(?P<content_type_id>\d+)/(?P<object_id>\d+)/$',
        'follow_unfollow', {'do_follow': False}, name='actstream_unfollow'),

    # Follower and Actor lists
    url(r'^followers/(?P<content_type_id>\d+)/(?P<object_id>\d+)/$',
        'followers', name='actstream_followers'),
    url(r'^actors/(?P<content_type_id>\d+)/(?P<object_id>\d+)/$',
        'actor', name='actstream_actor'),
    url(r'^actors/(?P<content_type_id>\d+)/$',
        'model', name='actstream_model'),

    url(r'^detail/(?P<action_id>\d+)/$', 'detail', name='actstream_detail'),
    url(r'^(?P<username>[-\w]+)/$', 'user', name='actstream_user'),
    url(r'^$', 'stream', name='actstream'),
)

clubs/urls.py
from django.conf.urls.defaults import patterns

#
# Handles the views for the Clubs application
#
urlpatterns = patterns ('clubs.views',
                        (r'^edit_court_setup/(?P<cs_id>\d+)/$', 'edit_court_setup'),
                        (r'^edit_court_setup/(?P<cs_id>\d+)/(?P<c_id>\d+)/$', 'edit_court_setup'),
                        (r'^toggle_available_court/(?P<c_id>\d+)/$', 'toggle_available_court'),
                        (r'^edit_court_properties/(?P<cs_id>\d+)/(?P<c_id>\d+)/$', 'edit_court_properties'),
                        (r'^save_court_vacancy/(?P<id>\d+)/$', 'save_court_vacancy'),
                        (r'^clone_court/(?P<c_id>\d+)/$', 'clone_court'),
                        (r'^delete_court/(?P<c_id>\d+)/$', 'delete_court'),
                        (r'^clone_court_setup/(?P<cs_id>\d+)/$', 'clone_court_setup'),
                        (r'^delete_court_setup/(?P<cs_id>\d+)/$', 'delete_court_setup'),
                        (r'^toggle_active_court_setup/(?P<cs_id>\d+)/$', 'toggle_active_court_setup'))

urls.py
from django.conf import settings
from django.conf.urls.defaults import patterns, include, url
from django.views.generic.simple import direct_to_template

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover ( )

urlpatterns = patterns ('',
    # url(r'^hocemtenis/', include('hocemtenis.foo.urls')),

    url (r'^$', 'ht.views.home', name='home'),
    url (r'^tos/$',
         direct_to_template,
         {'template': 'terms_of_service.html'},
         name='terms_of_service'),
    url (r'^wiki/', include ('wiki.urls')),
    url (r'^accounts/', include ('accounts.urls')),
    url (r'^clubs/', include ('clubs.urls')),
    url (r'^players/', include ('players.urls')),
    url (r'^reservations/', include ('reservations.urls')),
    url (r'^ranking/', include ('ranking.urls')),
    url (r'^user_messages/', include ('user_messages.urls')),
    url (r'^comments/', include ('comments.urls')),
    url (r'^activity/', include ('actstream.urls')),
    
    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
)

#
# Serve uploaded files only during development
#
if settings.DEBUG:
    urlpatterns += patterns ('',
        url (r'^media/(?P<path>.*)$',
             'django.views.static.serve',
             {'document_root': '%s/' % settings.MEDIA_ROOT,}),
   )

clubs/models.py
from django.db import models
from django.dispatch import receiver
from django.db.models import Count, Max
from django.core.exceptions import ValidationError
from django.db.models.signals import post_save, pre_delete
from django.utils.translation import ugettext
from django.utils.translation import ugettext_lazy as _

from clubs.managers import CourtManager, CourtSetupManager, VacancyManager
from accounts.models import ClubProfile



class CourtSetup (models.Model):
    """
    Enables different court configurations per club.-
    """
    name = models.CharField (max_length=100)
    club = models.ForeignKey (ClubProfile)
    is_active = models.BooleanField (default=False)
    objects = CourtSetupManager ( )

    def clean (self):
        """
        Only one court setup per club should be active.-
        """
        count = CourtSetup.objects.filter (club=self.club) \
                                  .filter (is_active=True)
        count = count.exclude (id=self.id) if self.id else count
        count = count.aggregate (Count ('id'))
        if (count['id__count'] > 0) and (self.is_active):
            raise ValidationError (_('Only one court setup may be active at once'))
    
    def __unicode__ (self):
        return self.name
    


@receiver (post_save, sender=ClubProfile)
def create_courtsetup (sender, instance, created, raw, **kwargs):
    """
    Callback function used whenever a new club profile is created.
    It creates a default court setup.-
    """
    #
    # Make sure a new club profile has been created by hand
    # (i.e. without fixtures)
    #
    if created and not raw:
        cs = CourtSetup.objects.create (name=ugettext('Default'),
                                        club=instance,
                                        is_active=True)
        cs.save ( )
        
        
            
class Court (models.Model):
    """
    A club's tennis court that is available for reservation.-
    """
    SURFACES = (('CL', _('Clay')),
                ('CE', _('Cement')),
                ('GR', _('Grass')),
                ('RU', _('Rubber')),
                ('CA', _('Carpet')))
    
    court_setup = models.ForeignKey (CourtSetup)
    number = models.IntegerField ( )
    indoor = models.BooleanField (default=False)
    light = models.BooleanField (default=True)
    surface = models.CharField (max_length=2,
                                choices=SURFACES,
                                default='CL')
    single_only = models.BooleanField (default=False)
    is_available = models.BooleanField (default=True)
    objects = CourtManager ( )
   
    class Meta:
        #
        # Don't allow a club to have repeated 
        # court numbers within an active setup
        # 
        unique_together = ('court_setup', 'number')
    
    def get_club (self):
        """
        Returns the club of this court.-
        """
        return self.court_setup.club
    
    def __unicode__ (self):
        return str (self.number)
 

 
@receiver (post_save, sender=CourtSetup)
def create_court (sender, instance, created, raw, **kwargs):
    """
    Callback function used whenever a new court setup is created.
    It creates one default court.-
    """
    #
    # Make sure a new court setup has been created by hand
    # (i.e. without fixtures)
    #
    if created and not raw:
        #
        # ... and that there are no courts yet
        #
        if Court.objects.get_count (instance) < 1:
            next_num = Court.objects.filter (court_setup=instance) \
                                    .aggregate (Max ('number'))
            if next_num['number__max']:
                next_num = next_num['number__max'] + 1
            else:
                next_num = 1
            c = Court.objects.create (court_setup=instance,
                                      number=next_num)
            c.save ( )



class Vacancy (models.Model):
    """
    Defines when and for how much a court is available for reservation.-
    """
    DAYS=((1, _('Monday')),
          (2, _('Tuesday')),
          (3, _('Wednesday')),
          (4, _('Thursday')),
          (5, _('Friday')),
          (6, _('Saturday')),
          (7, _('Sunday')))
    HOURS=((7, '7:00'),
           (8, '8:00'),
           (9, '9:00'),
           (10, '10:00'),
           (11, '11:00'),
           (12, '12:00'),
           (13, '13:00'),
           (14, '14:00'),
           (15, '15:00'),
           (16, '16:00'),
           (17, '17:00'),
           (18, '18:00'),
           (19, '19:00'),
           (20, '20:00'),
           (21, '21:00'),
           (22, '22:00'),
           (23, '23:00'),
           (24, '24:00'))
   
    court = models.ForeignKey (Court)
    day_of_week = models.IntegerField (choices=DAYS,
                                       default=1)
    available_from = models.IntegerField (choices=HOURS,
                                          default=8)
    available_to = models.IntegerField (choices=HOURS,
                                        default=9)
    price = models.DecimalField (max_digits=5,
                                 decimal_places=2,
                                 null=True,
                                 blank=True)
    objects = VacancyManager ( )
    
    class Meta:
        #
        # Don't allow court vacancies to overlap
        # 
        unique_together = ('court',
                           'day_of_week',
                           'available_from', 
                           'available_to')
        
    def clean (self):
        """
        Vacancy terms should be exactly one hour long.-
        """
        if (self.available_to - self.available_from) != 1:
            raise ValidationError (_('Vacancy terms should be one hour long'))
        
    def __unicode__ (self):
        return "%s, %s %s %s %s" % (self.get_day_of_week_display ( ),
                                    _('from'),
                                    self.available_from,
                                    _('to'),
                                    self.available_to)



@receiver (post_save, sender=Court)
def create_court_vacancy_terms (sender, instance, created, raw, **kwargs):
    """
    Callback function used whenever a new court is created.
    It creates all possible Vacancy terms for it.-
    """
    from ht_utils.models import insert_many
    #
    # Make sure a new court has been created by hand
    # (i.e. without fixtures)
    #
    if created and not raw:
        bulk = []
        days = [k for k,e in Vacancy.DAYS]
        hours = [k for k,e in Vacancy.HOURS]
        for d in days:
            for h in hours[:-1]:
                v = Vacancy (court=instance,
                             day_of_week=d,
                             available_from=h,
                             available_to=h+1,
                             price=None)
                bulk.append (v)
        insert_many (bulk)
 
 

@receiver(pre_delete, sender=Court)
def delete_associated_vacancy_terms (sender, instance, **kwargs):
    """
    Callback function used whenever a court is to be
    deleted. It deletes the associated Vacancy terms.-
    """
    #
    # Delete all Vacancy terms associated with this Court
    #
    Vacancy.objects.filter (court=instance).delete ( )

clubs/forms.py
from django import forms

from clubs.models import CourtSetup, Court
from accounts.models import ClubProfile



class EditCourtSetupForm (forms.ModelForm):
    """
    A form to add/change a court setup.-
    """
    club = forms.ModelChoiceField (queryset=ClubProfile.objects.all ( ),
                                   widget=forms.widgets.HiddenInput ( )) 
    class Meta:
        model = CourtSetup
       
        
class EditCourtPropertiesForm (forms.ModelForm):
    """
    A form to edit the court properties (e.g. surface, light, ...).-
    """
    court_setup = forms.ModelChoiceField (queryset=CourtSetup.objects.all ( ),
                                          widget=forms.widgets.HiddenInput ( ))
    class Meta:
        model = Court
        

templates/clubs/court_properties.html
{% load i18n %}
{% load static %}
{% get_static_prefix as STATIC_PREFIX %}

<p>
	<img src={% if court.surface == 'CL' %}
			     "{{ STATIC_PREFIX }}img/clay.png"
			 {% else %}{% if court.surface == 'CE' %}
			     "{{ STATIC_PREFIX }}img/cement.png"
			 {% else %}{% if court.surface == 'GR' %}
			     "{{ STATIC_PREFIX }}img/grass.png"
			 {% else %}{% if court.surface == 'RU' %}
			     "{{ STATIC_PREFIX }}img/cement.png"
			 {% else %}{% if court.surface == 'CA' %}
			     "{{ STATIC_PREFIX }}img/carpet.png"
			 {% endif %}{% endif %}{% endif %}{% endif %}{% endif %} title="{{ court.get_surface_display }}"/>
	{% if court.light %}
	   <img src="{{ STATIC_PREFIX }}img/light.png" title="{% trans "Artificial light" %}"/>
	{% else %}
	   <img src="{{ STATIC_PREFIX }}img/no_light.png" title="{% trans "No artificial light" %}"/>
	{% endif %}
	{% if court.indoor %}
	   <img src="{{ STATIC_PREFIX }}img/indoor.png" title="{% trans "Indoor" %}"/>
	{% else %}
	   <img src="{{ STATIC_PREFIX }}img/outdoor.png" title="{% trans "Outdoor" %}"/>
	{% endif %}
</p>

templates/clubs/court_setup.html
{% load i18n %}
{% load url from future %}
{% load static %}
{% get_static_prefix as STATIC_PREFIX %}

<script>
	/**
	 * change the target addresses of the Activate and Edit buttons dynamically
	 */
	$(document).ready (function ( ) {
		$(".panel_content input[type=radio][name=court_setup]").click (function ( ) {
			court_setup_id = this.value;
			$(".panel_buttons a#activate_court_setup").
				each (function ( ) {
					this.href = "{% url 'clubs.views.toggle_active_court_setup' 666 %}";	
					this.href = this.href.replace (666, court_setup_id);
				});
			$(".panel_buttons a#edit_court_setup").
				each (function ( ) {
					this.href = "{% url 'clubs.views.edit_court_setup' 666 %}";	
					this.href = this.href.replace (666, court_setup_id);
				});
		});
	});
</script>

<div class="panel">
	<div class="panel_title">
		<img src="{{ STATIC_PREFIX }}img/matches.png">
		<h2>{% trans 'Court setups' %}</h2>
	</div>
	<div class="panel_content">
		<fieldset>
		<ul>
	        {% for setup in court_setup_list %}
	        	<li>
		        	<label>
		        		<input type="radio" name="court_setup" value="{{ setup.id }}">
			                {% if setup.is_active %}
			                    <b>{{ setup.name }}
			                    {% trans "(active)" %}</b>
			                {% else %}
			                    {{ setup.name }}
			                {% endif %}
		            </label>
	            </li>
	        {% endfor %}
		</ul>
		</fieldset>
	</div>
	<div class="panel_buttons">
	    <a href="#" class="button" id="activate_court_setup">
	    	{% trans 'Activate' %}
	    </a>
	    <a href="#" class="button" id="edit_court_setup">
	    	{% trans 'Edit' %}
	    </a>
	</div>
</div>

templates/clubs/edit_court_properties.html
{% extends "base.html" %}
{% load i18n %}
{% load url from future %}


{% block user_content %}
	
    <h2>{% trans 'Court' %} {{ court.number }}</h2>
    <h4>- {{ court.court_setup }} -</h4>
    
    {% if form.errors %}
        {{ form.non_field_errors }}
    {% endif %}
    
    <div id="form">
        <form method="post" action="{% url 'clubs.views.edit_court_properties' court_setup_id court.id %}">
            {% csrf_token %}
            
            <div id="form_elem">  
                <label for="id_number">{% trans 'Number' %}</label>
                {{ form.number }}
                {{ form.number.errors }}
            </div>

            <div id="form_elem">  
                <label for="id_indoor">{% trans 'Indoor' %}</label>
                {{ form.indoor }}
                {{ form.indoor.errors }}
            </div>

            <div id="form_elem">  
                <label for="id_light">{% trans 'Light' %}</label>
                {{ form.light }}
                {{ form.light.errors }}
            </div>

            <div id="form_elem">  
                <label for="id_surface">{% trans 'Surface' %}</label>
                {{ form.surface }}
                {{ form.surface.errors }}
            </div>

            <div id="form_elem">  
                <label for="id_single_only">{% trans 'Single only?' %}</label>
                {{ form.single_only }}
                {{ form.single_only.errors }}
            </div>

            <div id="form_elem">  
                <label for="id_is_available">{% trans 'Is available?' %}</label>
                {{ form.is_available }}
                {{ form.is_available.errors }}
            </div>

            {{ form.court_setup }}
            
            <div id="form_action">
                <input type="submit" class="button" value="{% trans 'Save' %}"/>
            </div>
        </form>
    </div>

{% endblock %}

templates/clubs/edit_court_setup.html
{% extends "base.html" %}
{% load i18n %}
{% load url from future %}
{% load vacancy_tags %}

{% block user_content %}

    {% if form.errors %}
        {{ form.non_field_errors }}
    {% endif %}
    
    <div id="form">
        <form method="post" action="{% url 'clubs.views.edit_court_setup' court_setup_id %}">
            {% csrf_token %}
        
            <div id="form_elem">
                <label for="id_name">{% trans 'Name' %}</label>
                {{ form.name }}
                {{ form.name.errors }}
            </div>

            <div id="form_elem">  
	            <label for="id_is_active">
                	{% if form.is_active.value %}
                		{% trans '(currently active)' %}
	                {% endif %}
                </label>
                <span style="display:none;">
                    {{ form.is_active }}
                </span>
                {{ form.is_active.errors }}
            </div>

            {{ form.club }}
            
            <div id="form_action">
                <input type="submit" value="{% trans 'Save' %}" class="button"/>
            </div>
            <div id="form_action">
                <input type="button" value="{% trans 'Clone' %}" class="button"
                       onClick="window.location='{% url 'clubs.views.clone_court_setup' court_setup_id %}'">
            </div>
            <div id="form_action">
                <input type="button" value="{% trans 'Delete' %}" class="button"
                       onClick="window.location='{% url 'clubs.views.delete_court_setup' court_setup_id %}'">
            </div>
        </form>
    </div>
		
	<ol id="message_menu">
	    {% for court in court_list %}
	    	{% if court.id == selected_court.id %}
	    		<li class="current">
	    	{% else %}
	    		<li>
	    	{% endif %}
			<a href="{% url 'clubs.views.edit_court_setup' court_setup_id court.id %}">
				{% trans 'Court' %} {{ court.number }}
			</a></li>
		{% endfor %}
	</ol>
	
	<div id="court_setup">
	    {% for court in court_list %}
	    	{% if court.id == selected_court.id %}
		        {% if not court.is_available %}
		        	<h2>{% trans 'Not available for reservations' %}</h2>
		        	<br/>
		        	<p>
		        		<a href="{% url 'clubs.views.toggle_available_court' court.id %}" class="button">
		        			{% trans 'Activate' %}
		        		</a>
			            <a href="{% url 'clubs.views.edit_court_properties' court_setup_id court.id %}" class="button">
			                {% trans 'Properties' %}
			            </a>
		        	</p>
		        {% else %}
					<h2>{% trans 'Prices per day and hour' %}</h2>
					<br/> 
                	<form method="post" action="{% url 'clubs.views.save_court_vacancy' court.id %}">
                		{% csrf_token %}
                	
                		<span style="text-align:center;">	
		                    <a href="{% url 'clubs.views.delete_court' court.id %}" class="button">
		                    	{% trans 'Delete' %}
		                    </a> 
			        		<a href="{% url 'clubs.views.toggle_available_court' court.id %}" class="button">
			        			{% trans 'Deactivate' %}
			        		</a>
			        		<a href="{% url 'clubs.views.clone_court' court.id %}" class="button">
			        			{% trans 'Clone' %}
			        		</a>
				            <a href="{% url 'clubs.views.edit_court_properties' court_setup_id court.id %}" class="button">
				                {% trans 'Properties' %}
				            </a>
				            <a href="javascript:document.forms[1].submit();" class="button">
				            	{% trans 'Save' %}
				            </a>
		 		        </span>
		 		            
						<table class="reservation">
					        <thead>
					        	<tr>
				                <th scope="col">&nbsp;</th>
				                {% for day in day_list %}
				                    <th scope="col">{{ day.1 }}</th>
				                {% endfor %}
				                </tr>
					        </thead>
				            <tbody>
								{% for h, hour in hour_list %}
									<tr {% if forloop.counter|divisibleby:2 %}class="odd"{% endif %}>
										<th scope="row">
											{{ hour }}
					                  	</th>
						                {% vacancy_prices_per_day court h %}
					                </tr>
					            {% endfor %}
					        </tbody>
					       	<tfoot>
                                <tr>
                                    <th scope="row">
                                        &nbsp;
						       		</th>
                                    <td colspan="7">
									    &nbsp; 
				                    </td>
			                   	</tr>
					        </tfoot>
				        </table>
                    </form>
			    {% endif %}
			{% endif %}
	    {% endfor %}
	</div>
	
{% endblock %}

templates/clubs/home.html
{% extends "base.html" %}
{% load i18n %}
{% load static %}
{% get_static_prefix as STATIC_PREFIX %}
{% load url from future %}



{% block anonymous_content %}
	<div id="header_photo">
		<img src="{{ STATIC_PREFIX }}img/ball_closeup.jpg">
	</div>
{% endblock %}

{% block user_content %}
{% endblock %}

templates/clubs/vacancy_per_hour.html
{% load i18n %}
{% load url from future %}

{% for hour in hour_list %}
	<td>
	    {% if hour.vacancy.price and not hour.reservation %}
	        <a href="{% url 'reservations.views.player_edit' hour.vacancy.id ordinal_date %}"
	           class="small_button"
   			   title="{% trans 'Make reservation' %}">
	            {{ hour.vacancy.price }}
	        </a>
		{% else %}
	        <p>- - -</p>
		{% endif %}
	</td>
{% endfor %}

templates/clubs/vacancy_prices_per_day.html
{% for name,value in prices %}
	<td>
		<input type="text"
			   name="{{ name }}"
			   value="{{ value }}" 
			   size="10" maxlength="10">
	</td>
{% endfor %}