accounts/avatar/urls.py
from django.conf.urls.defaults import patterns, url

from .views import add, change, delete



urlpatterns = patterns ('accounts.avatar.views',
    url (r'^add/$', 
         add, 
         {'template_name': 'accounts/avatar/change.html',},
         name='avatar_add'),
    url (r'^change/$', 
         change,
         {'template_name': 'accounts/avatar/change.html',},
         name='avatar_change'),
    url (r'^delete/$', 
         delete,
         {'template_name': 'accounts/avatar/delete.html',},
         name='avatar_delete'),
    url('^render_primary/(?P<user>[\+\w]+)/(?P<size>[\d]+)/$', 'render_primary', name='avatar_render_primary'),    
)

accounts/urls.py
from django.contrib.auth import views as auth_views
from django.conf.urls.defaults import include, patterns, url
from django.views.generic.simple import direct_to_template

from registration.views import activate
from registration.views import register


#
# URLs for the Accounts & django-registration applications
#
urlpatterns = patterns ('',
                        url (r'^register/$',
                             register,
                             {'template_name':  'accounts/registration/register.html',
                              'success_url':    'accounts_registration_complete',
                              'disallowed_url': 'accounts_registration_disallowed',
                              'backend':        'registration.backends.default.DefaultBackend'},
                              name='accounts_registration_register'),
                        url (r'^register/complete/$',
                             direct_to_template,
                             {'template': 'accounts/registration/registration_complete.html'},
                             name='accounts_registration_complete'),
                        url (r'^register/closed/$',
                             direct_to_template,
                             {'template': 'accounts/registration/registration_closed.html'},
                             name='accounts_registration_disallowed'),
                        #
                        # Activation keys get matched by \w+ instead of the more specific
                        # [a-fA-F0-9]{40} because a bad activation key should still get to the view;
                        # that way it can return a sensible "invalid key" message instead of a
                        # confusing 404.
                        #
                        url (r'^activate/complete/$',
                             direct_to_template,
                             {'template': 'accounts/registration/activation_complete.html'},
                             name='accounts_registration_activation_complete'),
                        url (r'^activate/(?P<activation_key>\w+)/$',
                             activate,
                             {'template_name': 'accounts/registration/activation_error.html',
                              'success_url':   'accounts_registration_activation_complete',
                              'backend':       'registration.backends.default.DefaultBackend'},
                             name='accounts_registration_activate'),
                        #
                        # Login, logout and password related views
                        #
                        url (r'^login/$',
                             'accounts.views.login',
                             name='accounts_login'),
                        url (r'^logout/$',
                             'accounts.views.logout',
                             name='accounts_logout'),
                        url (r'^password/change/$',
                             'accounts.views.change_password',
                             name='accounts_change_password'),
                        url (r'^password/change/done/$',
                             'accounts.views.change_password_done',
                             name='accounts_change_password_done'),
                        #
                        # Profile-related views
                        #
                        url (r'^edit_player_profile/$', 
                             'accounts.views.edit_player_profile',
                             name='accounts_edit_player_profile'),
                        url (r'^edit_club_profile/$',
                             'accounts.views.edit_club_profile',
                             name='accounts_edit_club_profile'),
                        url (r'^profile/$',
                             'accounts.views.display_profile',
                             name='accounts_display_profile'),
                        #
                        # Login data related views
                        #
                        url (r'^login/change/$',
                             'accounts.views.edit_user_login_data',
                             name='accounts_edit_user_login_data'),
                        #
                        # Avatar related views
                        #
                        (r'^avatar/', include ('accounts.avatar.urls')),
                    )


"""
Not yet implemented


url (r'^password/reset/$',
     auth_views.password_reset,
     name='accounts_password_reset'),
url (r'^password/reset/confirm/(?P<uidb36>[0-9A-Za-z]+)-(?P<token>.+)/$',
     auth_views.password_reset_confirm,
     name='accounts_password_reset_confirm'),
url (r'^password/reset/complete/$',
     auth_views.password_reset_complete,
     name='accounts_password_reset_complete'),
url (r'^password/reset/done/$',
     auth_views.password_reset_done,
     name='accounts_password_reset_done'),
"""

actstream/urls.py
from django.conf.urls.defaults import *
from actstream import feeds

urlpatterns = patterns('actstream.views',
    # Syndication Feeds
    url(r'^feed/(?P<content_type_id>\d+)/(?P<object_id>\d+)/atom/$',
        feeds.AtomObjectActivityFeed(), name='actstream_object_feed_atom'),
    url(r'^feed/(?P<content_type_id>\d+)/(?P<object_id>\d+)/$',
        feeds.ObjectActivityFeed(), name='actstream_object_feed'),
    url(r'^feed/(?P<content_type_id>\d+)/atom/$',
        feeds.AtomModelActivityFeed(), name='actstream_model_feed_atom'),
    url(r'^feed/(?P<content_type_id>\d+)/(?P<object_id>\d+)/as/$',
        feeds.ActivityStreamsObjectActivityFeed(),
        name='actstream_object_feed_as'),
    url(r'^feed/(?P<content_type_id>\d+)/$',
        feeds.ModelActivityFeed(), name='actstream_model_feed'),
    url(r'^feed/$', feeds.UserActivityFeed(), name='actstream_feed'),
    url(r'^feed/atom/$', feeds.AtomUserActivityFeed(),
        name='actstream_feed_atom'),

    # Follow/Unfollow API
    url(r'^follow/(?P<content_type_id>\d+)/(?P<object_id>\d+)/$',
        'follow_unfollow', name='actstream_follow'),
    url(r'^unfollow/(?P<content_type_id>\d+)/(?P<object_id>\d+)/$',
        'follow_unfollow', {'do_follow': False}, name='actstream_unfollow'),

    # Follower and Actor lists
    url(r'^followers/(?P<content_type_id>\d+)/(?P<object_id>\d+)/$',
        'followers', name='actstream_followers'),
    url(r'^actors/(?P<content_type_id>\d+)/(?P<object_id>\d+)/$',
        'actor', name='actstream_actor'),
    url(r'^actors/(?P<content_type_id>\d+)/$',
        'model', name='actstream_model'),

    url(r'^detail/(?P<action_id>\d+)/$', 'detail', name='actstream_detail'),
    url(r'^(?P<username>[-\w]+)/$', 'user', name='actstream_user'),
    url(r'^$', 'stream', name='actstream'),
)

urls.py
from django.conf import settings
from django.conf.urls.defaults import patterns, include, url
from django.views.generic.simple import direct_to_template

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover ( )

urlpatterns = patterns ('',
    # url(r'^hocemtenis/', include('hocemtenis.foo.urls')),

    url (r'^$', 'ht.views.home', name='home'),
    url (r'^tos/$',
         direct_to_template,
         {'template': 'terms_of_service.html'},
         name='terms_of_service'),
    url (r'^wiki/', include ('wiki.urls')),
    url (r'^accounts/', include ('accounts.urls')),
    url (r'^clubs/', include ('clubs.urls')),
    url (r'^players/', include ('players.urls')),
    url (r'^reservations/', include ('reservations.urls')),
    url (r'^ranking/', include ('ranking.urls')),
    url (r'^user_messages/', include ('user_messages.urls')),
    url (r'^comments/', include ('comments.urls')),
    url (r'^activity/', include ('actstream.urls')),
    
    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
)

#
# Serve uploaded files only during development
#
if settings.DEBUG:
    urlpatterns += patterns ('',
        url (r'^media/(?P<path>.*)$',
             'django.views.static.serve',
             {'document_root': '%s/' % settings.MEDIA_ROOT,}),
   )

accounts/models.py
from abc import abstractmethod

from django.db import models
from django.dispatch import receiver
from django.core.exceptions import ValidationError
from django.db.models.signals import post_save
from django.utils.translation import ugettext_lazy as _
from django.db.models.signals import pre_delete
from django.contrib.auth.models import User

from actstream import action
from locations.models import City



class UserProfileManager (models.Manager):
    def get_players (self):
        """
        Returns all player profiles.-
        """
        return PlayerProfile.objects.all ( )


    def get_profile (self, username):
        """
        Returns the profile of the correct type (ie. player or club).-
        """
        ret_value = None
        u = User.objects.get (username=username)
        pp = PlayerProfile.objects.filter (user=u)
        if pp:
            ret_value = PlayerProfile.objects.get (user=u)

        cp = ClubProfile.objects.filter (user=u)
        if cp:
            ret_value = ClubProfile.objects.get (user=u)

        return ret_value


    def create_player_profile (self, username):
        """
        Associates a player profile with the received user and returns it.-
        """
        if self.get_profile (username) is None:
            u = User.objects.get (username=username)
            pp = PlayerProfile.objects.create (level='B',
                                               user=u)
            return pp
        else:
            #
            # return this player's existing profile
            #
            return self.get_profile (username)


    def create_club_profile (self, username, address, city, phone, company):
        """
        Associates a club profile to the received user. Because every created
        user is always first a player, the (possibly) existing player profile
        connected with the received 'username' is deleted, and thus the user
        is transformed from player to club.-
        """
        if self.get_profile (username) is None:
            u = User.objects.get (username=username)
            cp = ClubProfile.objects.create (user=u,
                                             address=address,
                                             city=city,
                                             phone=phone,
                                             company=company)
            return cp
        else:
            #
            # replace the (possible) player's profile with a club's one
            #
            if self.get_profile (username).is_player ( ):
                PlayerProfile.objects.filter (user__username=username).delete ( )
                u = User.objects.get (username=username)
                cp = ClubProfile.objects.create (user=u,
                                                 address=address,
                                                 city=city,
                                                 phone=phone,
                                                 company=company)
                return cp
            else:
                #
                # return the existing club profile
                #
                return self.get_profile (username)


class UserProfile (models.Model):
    """
    Holds extra data about the registered user of the site.
    If the foreign key to 'PlayerProfile' exists, then the user is
    registered as a player. When the foreign key to 'ClubProfile'
    exists, the user is registered as a club.
    It is an error for both foreign keys to be NULL (or None).-
    """
    user = models.ForeignKey (User,
                              unique=True,
                              blank=True)
    objects = UserProfileManager ( )

    class Meta:
        abstract = True

    @abstractmethod
    def is_player (self):
        """
        Returns TRUE if this profile belongs to a Player.-
        """
        return False

    @abstractmethod
    def is_club (self):
        """
        Returns TRUE is this profile belongs to a Club.-
        """
        return False

    def __unicode__ (self):
        return "Profile data for (%s)" % self.user.username



class PlayerProfile (UserProfile):
    """
    Holds extra data about the registered player.-
    """
    LEVELS = (('B', _('Beginner')),
              ('I', _('Intermediate')),
              ('A', _('Advanced')),
              ('F', _('Registered')))
    level = models.CharField (max_length=1,
                              choices=LEVELS,
                              default='B')
    male = models.BooleanField (default=True)
    right_handed = models.BooleanField (default=True)

    def clean (self):
        """
        Don't allow a player to have a club profile.-
        """
        if ClubProfile.objects.filter (user=self.user):
            raise ValidationError (_('This user has already been assigned a club profile'))

    def is_player (self):
        return True

    def is_club (self):
        return False


class ClubProfile (UserProfile):
    """
    Holds extra data about the registered club.-
    """
    address = models.CharField (max_length=200,
                                verbose_name=_('Address'))
    city = models.ForeignKey (City,
                              verbose_name=City._meta.verbose_name)
    phone = models.CharField (max_length=50,
                              verbose_name=_('Telephone numbers'))
    company = models.CharField (max_length=200,
                                verbose_name=_('Club or company name'))
    representative = models.CharField (max_length=100,
                                       default='-',
                                       verbose_name=_("Representative's full name"))
    representative_title = models.CharField (max_length=50,
                                             default='-',
                                             verbose_name=_("Representative's title"))
    tax_number = models.CharField (max_length=50,
                                   default='-',
                                   verbose_name=_('Tax number'))

    def clean (self):
        """
        Don't allow a club to have a player profile.-
        """
        if PlayerProfile.objects.filter (user=self.user):
            raise ValidationError (_('This user has already been assigned a player profile'))

    def is_player (self):
        return False

    def is_club (self):
        return True


@receiver (post_save, sender=ClubProfile, dispatch_uid="club_profile_post_save")
def club_profile_handler (sender, instance, created, **kwargs):
    """
    Callback function used whenever a club's profile is created or
    updated. It generates a user's action in the 'activity' app.-
    """
    if created:
        action.send (instance.user, verb='created', target=instance)
    else:
        action.send (instance.user, verb='updated', target=instance)



@receiver (post_save, sender=User, dispatch_uid="user_profile_post_save")
def link_user_with_player_profile (sender, instance, created, **kwargs):
    """
    Callback function used whenever an existing user's data are updated
    or a new user is created. In this case, a player's profile is created
    and linked to it.
    """
    if created:
        #
        # create a new player profile and link it with the user
        #
        pp = UserProfile.objects.create_player_profile (instance.username)
        action.send (instance, verb='has profile', target=pp)
        
        
@receiver (pre_delete, sender=User, dispatch_uid="user_profile_pre_delete")
def delete_associated_profile (sender, instance, **kwargs):
    """
    Callback function used whenever a user is to be
    deleted. It deletes the associated Player/Club Profile and
    generates a user's action in the 'activity' app.-
    """
    #
    # Make sure a player/club profile exists, associated
    # with the user profile being deleted
    #
    prof = UserProfile.objects.get_profile (instance.username)
    if prof:
        if prof.is_player ( ):
            PlayerProfile.objects.get (pk=prof.id).delete ( )
        if prof.is_club ( ):
            ClubProfile.objects.get (pk=prof.id).delete ( )
        action.send (instance, verb='deleted', target=prof)

templates/accounts/change_password.html
{% extends "base.html" %}
{% load i18n %}
{% load url from future %}

{% load ht_utils_tags %}

{% block user_content %}

	{% text_only _('You may change your password in this form.') _('Password change') '' '' 0 %} 
	
	{% vertical_form form 'accounts_change_password' _('Change') 'accounts_change_password_done' %}
	
{% endblock %}

templates/accounts/change_password_done.html
{% extends "base.html" %}
{% load i18n %}
{% load url from future %}

{% load ht_utils_tags %}

{% block user_content %}

	{% text_only _('Your password has been successfully changed.') _('Password changed') 'OK' 'accounts_display_profile' %} 
	
{% endblock %}

templates/accounts/club_information.html
{% load i18n %} 
{% load url from future %}
{% load static %}
{% get_static_prefix as STATIC_PREFIX %}

<div class="panel">
	{% if club %}
		<div class="panel_title">
			<img src="{{ STATIC_PREFIX }}img/personal_information.png">
			<h2>{% trans 'Institutional data' %}</h2>
		</div>
		<div class="panel_content">
			<ul>
				<li>{{ club.company }}</li>
                <li>{{ club.address }}, {{ club.city }}</li>
				<li>{{ club.phone }}</li>
                <li>{{ club.user.email }}</li>
			</ul>
		</div>
        <div class="panel_buttons">
            <a href="{% url 'accounts_change_password' %}" class="button">
                {% trans 'Change password' %}
            </a>
            <a href="{% url 'accounts_edit_club_profile' %}" class="button">
                {% trans 'Edit' %}
            </a>
		</div>
	{% endif %}
</div>

templates/accounts/club_profile_base.html
{% extends "base.html" %}
{% load i18n %}
{% load url from future %}


{% block user_content %}

	{% block tab_menu %}
	    <ol id="message_menu">
	        <li {% block login_data_current %}{% endblock %}>
	            <a href="{% url 'accounts_edit_user_login_data' %}">
	                {% trans 'Login data' %}
	            </a>
	        </li>
	        <li {% block profile_data_current %}{% endblock %}>
	            <a href="{% url 'accounts_edit_club_profile' %}">
	                {% trans 'Institutional data' %}
	            </a>
	        </li>
	        <li {% block avatar_data_current %}{% endblock %}>
	            <a href="{% url 'avatar_change' %}">
	                {% trans 'Badge' %}
	            </a>
	        </li>
	    </ol>
	{% endblock %}

	{% block tab_content %}
	{% endblock %}
	
{% endblock %}

templates/accounts/display_club_profile.html
{% extends "base.html" %}
{% load i18n %}

{% load account_tags %}
{% load court_tags %}


{% block user_content %}
	<div class="profile_panels_left">
		{% club_information user %}
	</div>
	
	<div class="profile_panels_right">
    	{% court_setup user %}			
	</div>
{% endblock %}

templates/accounts/display_player_profile.html
{% extends "base.html" %}
{% load i18n %}
{% load static %}
{% get_static_prefix as STATIC_PREFIX %}
{% load url from future %}
{% load availability %}
{% load invitations %}
{% load played_matches %}
{% load account_tags %}



{% block user_content %}
	<div class="profile_panels_left">
		{% availability user %}
		
		{% played_matches user %}
		
		{% player_information user %}
	</div>
	
	<div class="profile_panels_right">
		{% display_invitations user %}
		
		<div class="panel">
			<div class="panel_title">
				<img src="{{ STATIC_PREFIX }}img/ads_activity.png">
				<h2>{% trans 'Ads' %}</h2>
			</div>
			<div class="panel_content">
				<p>
				    {% trans "The ads you publish, including the comments people post on them, are displayed here." %}
				</p>
				<p>
				    {% trans "You may also follow other people's ads that may interest you. Try finding that racquet you always dreamed about!" %}
				</p>
			</div>
			<div class="panel_buttons">
			    <a href="#" class="button">{% trans 'Search' %}</a>
			</div>
		</div>
	</div>
{% endblock %}

templates/accounts/edit_club_profile.html
{% extends "accounts/club_profile_base.html" %}

{% load ht_utils_tags %}


{% block profile_data_current %}
	class="current"
{% endblock %}

{% block tab_content %}
	{% vertical_form form 'accounts_edit_club_profile' _('Save') next_url %}
{% endblock %}

templates/accounts/edit_player_profile.html
{% extends "base.html" %}
{% load i18n %}
{% load url from future %}

{% block anonymous_content %}

	{% if form.errors %}
		{{ form.non_field_errors }}
	{% endif %}

    <div id="form">
		<form method="post" action="{% url 'accounts.views.edit_player_profile' %}">
		    {% csrf_token %}
		    
            <div id="form_elem">
                <label for="id_first_name">{% trans 'First name' %}</label>
                {{ form.first_name }}
                {{ form.first_name.errors }}
            </div>
            
            <div id="form_elem">
                <label for="id_last_name">{% trans 'Last name' %}</label>
                {{ form.last_name }}
                {{ form.last_name.errors }}
            </div>
            
            <div id="form_elem">
                <label for="id_level">{% trans 'Game level' %}</label>
                {{ form.level }}
                {{ form.level.errors }}
            </div>
            
            <div id="form_elem">
                <label for="id_male">{% trans 'Male?' %}</label>
                {{ form.male }}
                {{ form.male.errors }}
            </div>
            
            <div id="form_elem">
                <label for="id_right_handed">{% trans 'Right handed?' %}</label>
                {{ form.right_handed }}
                {{ form.right_handed.errors }}
            </div>
            
            {{ form.user }}
            {{ form.next }}
            
			<div id="form_action">
			    <input type="submit" value="{% trans 'Save' %}" class="button"/>
			</div>
		</form>
	</div>	
{% endblock %}

templates/accounts/edit_user_login_data.html
{% extends "accounts/club_profile_base.html" %}

{% load ht_utils_tags %}


{% block login_data_current %}
	class="current"
{% endblock %}

{% block tab_content %}
	{% vertical_form form 'accounts_edit_user_login_data' _('Save') next_url %}
{% endblock %}

templates/accounts/login.html
{% extends "base.html" %}
{% load i18n %}
{% load url from future %}

{% block anonymous_content %}

	{% if form.errors %}
		<p>{% trans 'Wrong email address or password' %}</p>
	{% endif %}
	
	<div id="form">
		<form method="post" action="{% url 'accounts.views.login' %}">
			{% csrf_token %}
		
            <div id="form_elem">
                <label for="id_username">{% trans 'User name' %}</label>
                {{ form.username }}
                {{ form.username.errors }}
            </div>
            
            <div id="form_elem">
                <label for="id_password">{% trans 'Password' %}</label>
                {{ form.password }}
                {{ form.password.errors }}
            </div>
			
			<input type="hidden" name="next" {% if not next %}
												value="/"
											 {% else %}
											 	value="{{ next }}"
											 {% endif %} />
			<div id="form_action">
				<input type="submit" value="{% trans 'Login' %}" class="button"/>
			</div>
		</form>
	</div>
{% endblock %}

templates/accounts/player_information.html
{% load i18n %}
{% load url from future %}
{% load static %}
{% get_static_prefix as STATIC_PREFIX %}


<div class="panel">
    {% if player %}
		<div class="panel_title">
			<img src="{{ STATIC_PREFIX }}img/personal_information.png">
			<h2>{% trans 'Personal information' %}</h2>
		</div>
		<div class="panel_content">
			<ul>
				<li>
					{{ player.user.first_name }}
					{{ player.user.last_name }}
					
					{% if player.male %}
				        {% trans '(Male)' %}
				    {% else %}
				        {% trans '(Female)' %}
				    {% endif %}
				</li>
				<li>
				  {% if player.right_handed %}
				      {% trans 'Right-handed' %}
				  {% else %}
				      {% trans 'Left-handed' %}
				  {% endif %}
				</li>  
				<li>{{ player.get_level_display }}</li>
				<li>{{ player.user.email }}</li>
			</ul>
		</div>
		<div class="panel_buttons">
			<a href="{% url 'accounts.views.edit_player_profile' %}" class="button">
			   {% trans 'Edit' %}
			</a>
		</div>
	{% endif %}
</div>

templates/accounts/user_menu.html
{% load i18n %}
{% load url from future %}

<ul>
    {% if user.is_authenticated %}
        {% if profile %}
			<li>
				<a href="{% url 'accounts_display_profile' %}">
					{% trans 'Profile' %}
				</a>
			</li>
            {% if profile.is_club %}
				<li>
					<a href="{% url 'reservations.views.club_view' %}">
						{% trans 'Reservations' %}
					</a>
				</li>
			{% endif %}
		{% endif %}
	{% endif %}
</ul>