accounts/avatar/urls.py
from django.conf.urls.defaults import patterns, url

from .views import add, change, delete



urlpatterns = patterns ('accounts.avatar.views',
    url (r'^add/$', 
         add, 
         {'template_name': 'accounts/avatar/change.html',},
         name='avatar_add'),
    url (r'^change/$', 
         change,
         {'template_name': 'accounts/avatar/change.html',},
         name='avatar_change'),
    url (r'^delete/$', 
         delete,
         {'template_name': 'accounts/avatar/delete.html',},
         name='avatar_delete'),
    url('^render_primary/(?P<user>[\+\w]+)/(?P<size>[\d]+)/$', 'render_primary', name='avatar_render_primary'),    
)

actstream/urls.py
from django.conf.urls.defaults import *
from actstream import feeds

urlpatterns = patterns('actstream.views',
    # Syndication Feeds
    url(r'^feed/(?P<content_type_id>\d+)/(?P<object_id>\d+)/atom/$',
        feeds.AtomObjectActivityFeed(), name='actstream_object_feed_atom'),
    url(r'^feed/(?P<content_type_id>\d+)/(?P<object_id>\d+)/$',
        feeds.ObjectActivityFeed(), name='actstream_object_feed'),
    url(r'^feed/(?P<content_type_id>\d+)/atom/$',
        feeds.AtomModelActivityFeed(), name='actstream_model_feed_atom'),
    url(r'^feed/(?P<content_type_id>\d+)/(?P<object_id>\d+)/as/$',
        feeds.ActivityStreamsObjectActivityFeed(),
        name='actstream_object_feed_as'),
    url(r'^feed/(?P<content_type_id>\d+)/$',
        feeds.ModelActivityFeed(), name='actstream_model_feed'),
    url(r'^feed/$', feeds.UserActivityFeed(), name='actstream_feed'),
    url(r'^feed/atom/$', feeds.AtomUserActivityFeed(),
        name='actstream_feed_atom'),

    # Follow/Unfollow API
    url(r'^follow/(?P<content_type_id>\d+)/(?P<object_id>\d+)/$',
        'follow_unfollow', name='actstream_follow'),
    url(r'^unfollow/(?P<content_type_id>\d+)/(?P<object_id>\d+)/$',
        'follow_unfollow', {'do_follow': False}, name='actstream_unfollow'),

    # Follower and Actor lists
    url(r'^followers/(?P<content_type_id>\d+)/(?P<object_id>\d+)/$',
        'followers', name='actstream_followers'),
    url(r'^actors/(?P<content_type_id>\d+)/(?P<object_id>\d+)/$',
        'actor', name='actstream_actor'),
    url(r'^actors/(?P<content_type_id>\d+)/$',
        'model', name='actstream_model'),

    url(r'^detail/(?P<action_id>\d+)/$', 'detail', name='actstream_detail'),
    url(r'^(?P<username>[-\w]+)/$', 'user', name='actstream_user'),
    url(r'^$', 'stream', name='actstream'),
)

players/urls.py
from django.conf.urls.defaults import patterns

#
# Handles the views for the Players application
#
urlpatterns = patterns ('players.views',
                        (r'^add_vacancy$', 'add_vacancy'),
                        (r'^edit_vacancy$', 'edit_vacancy'),
                        (r'^delete_vacancy/(?P<id>\d+)/$', 'delete_vacancy'),
                        (r'^search_opponent$', 'search_opponent'),
                        (r'^invite_player/(?P<id>\d+)/$', 'invite_player'))

urls.py
from django.conf import settings
from django.conf.urls.defaults import patterns, include, url
from django.views.generic.simple import direct_to_template

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover ( )

urlpatterns = patterns ('',
    # url(r'^hocemtenis/', include('hocemtenis.foo.urls')),

    url (r'^$', 'ht.views.home', name='home'),
    url (r'^tos/$',
         direct_to_template,
         {'template': 'terms_of_service.html'},
         name='terms_of_service'),
    url (r'^wiki/', include ('wiki.urls')),
    url (r'^accounts/', include ('accounts.urls')),
    url (r'^clubs/', include ('clubs.urls')),
    url (r'^players/', include ('players.urls')),
    url (r'^reservations/', include ('reservations.urls')),
    url (r'^ranking/', include ('ranking.urls')),
    url (r'^user_messages/', include ('user_messages.urls')),
    url (r'^comments/', include ('comments.urls')),
    url (r'^activity/', include ('actstream.urls')),
    
    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
)

#
# Serve uploaded files only during development
#
if settings.DEBUG:
    urlpatterns += patterns ('',
        url (r'^media/(?P<path>.*)$',
             'django.views.static.serve',
             {'document_root': '%s/' % settings.MEDIA_ROOT,}),
   )

players/models.py
from accounts.models import PlayerProfile
from locations.models import City

from django.db import models
from django.utils.translation import ugettext_lazy as _

        

class Vacancy (models.Model):
    """
    Defines a time and place interval for a player to play.-
    """
    DAYS=(('WD', _('Week days')),
          ('WN', _('Weekends')),
          ('SA', _('Saturdays')),
          ('SU', _('Sundays')),
          ('MO', _('Mondays')),
          ('TU', _('Tuesdays')),
          ('WE', _('Wednesdays')),
          ('TH', _('Thursdays')),
          ('FR', _('Fridays')))
    FROM_TO=(('F', _('from')),
             ('T', _('up to')))
    HOURS=(('07', '7:00'),
           ('08', '8:00'),
           ('09', '9:00'),
           ('10', '10:00'),
           ('11', '11:00'),
           ('12', '12:00'),
           ('13', '13:00'),
           ('14', '14:00'),
           ('15', '15:00'),
           ('16', '16:00'),
           ('17', '17:00'),
           ('18', '18:00'),
           ('19', '19:00'),
           ('20', '20:00'),
           ('21', '21:00'),
           ('22', '22:00'),
           ('23', '23:00'))
    player = models.ForeignKey (PlayerProfile,
                                null=False,
                                blank=False)
    day = models.CharField (max_length=2,
                            choices=DAYS,
                            default='WN',
                            null=False,
                            blank=False)
    from_to = models.CharField (max_length=1,
                                choices=FROM_TO,
                                default='F',
                                null=False,
                                blank=False)
    hour = models.CharField (max_length=2,
                             choices=HOURS,
                             default='07',
                             null=False,
                             blank=False)
    city = models.ForeignKey (City,
                              null=False,
                              blank=False)

    @staticmethod
    def get_weekdays ( ):
        """
        Returns a list with the week days.-
        """
        ret_value = [Vacancy.DAYS[4][0],
                     Vacancy.DAYS[5][0],
                     Vacancy.DAYS[6][0],
                     Vacancy.DAYS[7][0],
                     Vacancy.DAYS[8][0]]
        return ret_value
    
    
    @staticmethod
    def get_weekends ( ):
        """
        Returns a list with the weekend days.-
        """
        ret_value = list ( )
        ret_value.append (Vacancy.DAYS[2][0])
        ret_value.append (Vacancy.DAYS[3][0])
        return ret_value
    

players/forms.py
from django import forms
from django.forms.models import ModelChoiceField
from django.forms.widgets import HiddenInput
from django.utils.translation import ugettext_lazy as _

from players.models import Vacancy
from accounts.models import PlayerProfile
from locations.models import City



class SearchOpponentForm (forms.Form):
    """
    A form to look for an opponent.-
    """
    WHEN_CHOICES = list (Vacancy.DAYS)
    WHEN_CHOICES.insert (0, ('XX', _('-- any day --')))
    when = forms.TypedChoiceField (choices = WHEN_CHOICES,
                                   initial='XX',
                                   required=False)
    where = forms.ModelChoiceField (queryset=City.objects.all ( ),
                                    empty_label=_('-- anywhere --'),
                                    required=False)
        
        
class EditVacancyForm (forms.ModelForm):
    """
    A form to add/change a player's vacancy.-
    """
    player = ModelChoiceField (queryset=PlayerProfile.objects.all ( ),
                               widget=HiddenInput ( ))
    class Meta:
        model = Vacancy
        widgets = {'from_to': forms.widgets.RadioSelect ( ),}
        

players/views.py
import random

from django.http import Http404
from django.shortcuts import render_to_response, get_object_or_404
from django.template.context import RequestContext
from django.utils.translation import ugettext as _
from django.contrib.auth.decorators import login_required

import user_messages
from accounts.models import PlayerProfile, UserProfile
from players.models import Vacancy
from players.forms import EditVacancyForm, SearchOpponentForm



@login_required
def edit_vacancy (request):
    """
    Changes a player's availability for play.-
    """
    player = UserProfile.objects.get_profile (request.user.username)
    
    if player.is_player ( ):
        player_profile = request.user.get_profile ( ).player_profile
        player_vacancy = Vacancy.objects.filter (player=player)
        
        if request.method == 'POST':
            form = EditVacancyForm (request.POST)
        else:
            v = Vacancy ( )
            v.player = player_profile
            form = EditVacancyForm (instance=v)
           
        return render_to_response ('players/vacancy.html',
                                   {'form': form,
                                    'player_vacancy': player_vacancy},
                                   context_instance=RequestContext(request))
    else:
        raise Http404
    
    
    
@login_required
def add_vacancy (request):
    """
    Adds a player's time and place for play.-
    """
    #
    # Create a new form with the received data ...
    #
    form = EditVacancyForm (request.POST or None)
    #
    # ... add the data about the logged-in user ...
    #
    form.instance.player = request.user.get_profile ( ).player_profile
    #
    # ... find out if everything is valid
    #
    if (form.is_valid ( )):
        form.save (commit=True)
    return edit_vacancy (request)


@login_required
def delete_vacancy (request, id):
    """
    Deletes the vacancy with the received id.-
    """
    v = get_object_or_404 (Vacancy, pk=id)
    v.delete ( )
    return edit_vacancy (request)


@login_required
def invite_player (request, id):
    """
    Sends an invitation to another player for a tennis match.-
    """
    v = get_object_or_404 (Vacancy, pk=id)
    subject = '[%s] %s %s %s %s %s' % (_('Invitation'),
                                       v.get_day_display ( ),
                                       v.get_from_to_display ( ),
                                       v.get_hour_display ( ),
                                       _('in'),
                                       v.city)
    return user_messages.views.compose (request,
                                        recipient=v.player.user_profile.user.username,
                                        subject=subject)


def search_opponent (request, city_id=None):
    """
    Displays the search form to look for an opponent. It also displays
    the results of the search. When called with GET, random opponents 
    are displayed.-
    """
    #
    # exclude the player making the search
    #
    if request.user.is_authenticated ( ):
        player = UserProfile.objects.get_profile (request.user.username)
        if player.is_player ( ):
            vacancies = Vacancy.objects.exclude (player=player)
        else:
            vacancies = Vacancy.objects.all ( )
    else:
        vacancies = Vacancy.objects.all ( )
    
    if request.method == 'POST':
        #
        # search opponents, available on the same days and cities
        #
        form = SearchOpponentForm (request.POST, 
                                   label_suffix=' ')
        if form.is_valid ( ):
            when = [ form.cleaned_data['when'] ]
            where = form.cleaned_data['where'] if city_id is None else city_id 
            #
            # add filters by day
            #
            if ('XX' not in when):
                #
                # during week days?
                #
                if ('WD' in when):
                    when = when + Vacancy.get_weekdays ( )
                elif (form.cleaned_data['when'] in Vacancy.get_weekdays ( )):
                    when.append ('WD')
                #
                # during weekends?
                #
                if ('WN' in when):
                    when = when + Vacancy.get_weekends ( )
                elif (form.cleaned_data['when'] in Vacancy.get_weekends ( )):
                    when.append ('WN')
                vacancies = vacancies.filter (day__in=when)
            #
            # add filters by city
            #
            if (where is not None):
                vacancies = vacancies.filter (city=where)
            #
            # get the players matching the vacancies
            #
            players_qset = PlayerProfile.objects.filter (pk__in=vacancies.values_list('player_id')) 
    else:
        form = SearchOpponentForm (label_suffix=' ')
        #
        # display random player's vacancies, if any
        #
        players = vacancies.distinct ( ).values_list ('player_id')
        if players:
            rand_pl = random.randint (0, players.count ( ) - 1)
            players_qset = PlayerProfile.objects.filter (pk=players[rand_pl][0])
        else:
            players_qset = None

    return render_to_response ('players/opponent.html',
                               {'form': form,
                                'players_qset': players_qset},
                               context_instance=RequestContext(request))

templates/players/availability.html
{% load i18n %}
{% load url from future %}
{% load static %}
{% get_static_prefix as STATIC_PREFIX %}


<div class="panel">
	<div class="panel_title">
		<img src="{{ STATIC_PREFIX }}img/availability.png">
		<h2>{% trans 'Availability' %}</h2>
	</div>
	<div class="panel_content">
	    <ul>
	        {% for vacancy in vacancy_list %}
	        	<li>
	            	{{ vacancy.get_day_display }}
	            	{{ vacancy.get_from_to_display }}
	            	{{ vacancy.get_hour_display }},
	            	
	            	{% if vacancy.from_to == 'F' %}
	            		{% trans 'and later' %},
	            	{% endif %}
	            	
	            	{% trans 'in' %}
	            	{{ vacancy.city }}.
	            
	            	{% if delete %}	
	            		<a href="{% url 'players.views.delete_vacancy' vacancy.id %}">
		            		{% trans 'Delete' %}
	            		</a>
	            	{% endif %}
	            	{% if invite %}
	            		<a href="{% url 'players.views.invite_player' vacancy.id %}">
		            		{% trans 'Invite' %}
	            		</a>
					{% endif %}            	
	            </li>
	        {% empty %}
	           <p>{% trans 'Tell us when you have time, so that other people will be able to invite you for a match!' %}</p>
	        {% endfor %}
	    </ul>
	</div>
	<div class="panel_buttons">
		<a href="{% url 'players.views.edit_vacancy' %}" class="button">
			{% trans 'Edit' %}
		</a>
	</div>
</div>

templates/players/home.html
{% extends "base.html" %}
{% load i18n %}
{% load static %}
{% get_static_prefix as STATIC_PREFIX %}
{% load url from future %}



{% block anonymous_content %}
	<div id="header_photo">
		<img src="{{ STATIC_PREFIX }}img/rogelio.jpg">
		<br>
	</div>
	
	<div id="site_sections">
		<article>
			<div id="section">
				<a href="{% url 'players.views.search_opponent' %}">
					<img src="{{ STATIC_PREFIX }}img/find_partner.png">
				</a>
			</div>
			<div id="section">
				<a href="{% url 'reservations.views.search' %}">
					<img src="{{ STATIC_PREFIX }}img/find_court.png">
				</a>
			</div>
			<div id="section">
				<a href="#">
					<img src="{{ STATIC_PREFIX }}img/ads.png">
				</a>
			</div>
			<div id="section">
				<a href="#">
					<img src="{{ STATIC_PREFIX }}img/wiki.png">
				</a>
			</div>
		</article>
	</div>
{% endblock %}

{% block user_content %}
{% endblock %}

templates/players/opponent.html
{% extends "base.html" %}
{% load i18n %}
{% load url from future %}
{% load availability %}



{% block anonymous_content %}
	<div id="header_photo">
		<img src="{{ STATIC_PREFIX }}img/ball_closeup.jpg">
		<br>
	</div>

    {% if form.errors %}
        {{ form.non_field_errors }}
    {% endif %}

	<div id="form">
        <form method="post" action="{% url 'players.views.search_opponent' %}">
            {% csrf_token %}

		    <div id="form_elem">
			    {{ form.when.errors }}
			    <label for="id_when">{% trans 'I would like to play on' %}</label>
			    {{ form.when }}
	        </div>

		    <div id="form_elem">
			    {{ form.where.errors }}
			    <label for="id_where">{% trans 'near' %}</label>
			    {{ form.where }}
	        </div>

            <div id="form_action">
                <input type="submit" value="{% trans 'Search' %}" class="button"/>
            </div>
        </form>
	</div>
	
	<article>
		<div id="opponent_panels">
			<header>
				{% if not players_qset %}
					<script>
                        function oppByCity( ) 
                        {
                            document.forms[0].when.value='XX';
                            document.forms[0].submit ( );
                            return;
                        }
					</script>
					<h3>{% trans 'No players found to play on the selected days' %}.</h3>
					<h3>{% trans 'Try to find' %}
						<a href="javascript:oppByCity();">
							{% trans 'players nearby' %}
						</a>
					</h3>
				{% endif %}
			</header>
			
			{% for player in players_qset.iterator %}
				<div id="{% cycle 'opponent_panels_left' 'opponent_panels_left' 'opponent_panels_right' 'opponent_panels_right' %}">
					<div id="opponent_panel">
						<div id="opponent_panel_title">
			        		<a href="{% url 'ranking.views.display_matches' player.user_profile.user.id %}">
			        			<img src="{{ STATIC_PREFIX }}img/tennis_player.jpg">
				        		{{ player.user_profile.user.username }}
			        		</a>
			        	</div>
						<div id="opponent_panel_content">
							{% availability player.user_profile.user 1 0 %}
		        		</div>
					</div>
				</div>
			{% endfor %}
		</div>
	</article>
{% endblock %}

templates/players/vacancy.html
{% extends "base.html" %}
{% load i18n %}
{% load url from future %}
{% load availability %}

{% block user_content %}

	{% availability user %}

	{% if form.errors %}
		<p>{% trans 'You have an error' %}</p>
	{% endif %}
	<form method="post" action="{% url 'players.views.add_vacancy' %}">
		{% csrf_token %}
		{{ form.as_p }}
		<input type="submit" value="{% trans 'Add' %}"/>
	</form>

{% endblock %}