actstream/urls.py
from django.conf.urls.defaults import *
from actstream import feeds

urlpatterns = patterns('actstream.views',
    # Syndication Feeds
    url(r'^feed/(?P<content_type_id>\d+)/(?P<object_id>\d+)/atom/$',
        feeds.AtomObjectActivityFeed(), name='actstream_object_feed_atom'),
    url(r'^feed/(?P<content_type_id>\d+)/(?P<object_id>\d+)/$',
        feeds.ObjectActivityFeed(), name='actstream_object_feed'),
    url(r'^feed/(?P<content_type_id>\d+)/atom/$',
        feeds.AtomModelActivityFeed(), name='actstream_model_feed_atom'),
    url(r'^feed/(?P<content_type_id>\d+)/(?P<object_id>\d+)/as/$',
        feeds.ActivityStreamsObjectActivityFeed(),
        name='actstream_object_feed_as'),
    url(r'^feed/(?P<content_type_id>\d+)/$',
        feeds.ModelActivityFeed(), name='actstream_model_feed'),
    url(r'^feed/$', feeds.UserActivityFeed(), name='actstream_feed'),
    url(r'^feed/atom/$', feeds.AtomUserActivityFeed(),
        name='actstream_feed_atom'),

    # Follow/Unfollow API
    url(r'^follow/(?P<content_type_id>\d+)/(?P<object_id>\d+)/$',
        'follow_unfollow', name='actstream_follow'),
    url(r'^unfollow/(?P<content_type_id>\d+)/(?P<object_id>\d+)/$',
        'follow_unfollow', {'do_follow': False}, name='actstream_unfollow'),

    # Follower and Actor lists
    url(r'^followers/(?P<content_type_id>\d+)/(?P<object_id>\d+)/$',
        'followers', name='actstream_followers'),
    url(r'^actors/(?P<content_type_id>\d+)/(?P<object_id>\d+)/$',
        'actor', name='actstream_actor'),
    url(r'^actors/(?P<content_type_id>\d+)/$',
        'model', name='actstream_model'),

    url(r'^detail/(?P<action_id>\d+)/$', 'detail', name='actstream_detail'),
    url(r'^(?P<username>[-\w]+)/$', 'user', name='actstream_user'),
    url(r'^$', 'stream', name='actstream'),
)

clubs/urls.py
from django.conf.urls.defaults import patterns

#
# Handles the views for the Clubs application
#
urlpatterns = patterns ('clubs.views',
                        (r'^edit_court_setup/(?P<cs_id>\d+)/$', 'edit_court_setup'),
                        (r'^edit_court_setup/(?P<cs_id>\d+)/(?P<c_id>\d+)/$', 'edit_court_setup'),
                        (r'^toggle_available_court/(?P<c_id>\d+)/$', 'toggle_available_court'),
                        (r'^edit_court_properties/(?P<cs_id>\d+)/(?P<c_id>\d+)/$', 'edit_court_properties'),
                        (r'^save_court_vacancy/(?P<id>\d+)/$', 'save_court_vacancy'),
                        (r'^clone_court/(?P<c_id>\d+)/$', 'clone_court'),
                        (r'^delete_court/(?P<c_id>\d+)/$', 'delete_court'),
                        (r'^clone_court_setup/(?P<cs_id>\d+)/$', 'clone_court_setup'),
                        (r'^delete_court_setup/(?P<cs_id>\d+)/$', 'delete_court_setup'),
                        (r'^toggle_active_court_setup/(?P<cs_id>\d+)/$', 'toggle_active_court_setup'))

reservations/urls.py
from django.conf.urls.defaults import patterns, url

#
# Handles the views for the Players application
#
urlpatterns = patterns ('reservations.views',
                        (r'^search$', 'search'),
                        (r'^club_view$', 'club_view'),
                        (r'^cancel/(?P<r_id>\d+)/$', 'cancel'),
                        url (r'^player_edit/(?P<v_id>\d+)/(?P<ordinal_date>\d+)/$',
                             'player_edit',
                             name='reservations_edit_player'),
                        url (r'^club_edit/(?P<v_id>\d+)/(?P<ordinal_date>\d+)/$',
                             'club_edit',
                             name='reservations_edit_club'),
                        (r'^transfer_or_delete/(?P<cs_id>\d+)/$', 'transfer_or_delete'),
                        (r'^transfer_or_delete/(?P<cs_id>\d+)/(?P<c_id>\d+)/$', 'transfer_or_delete')
                        )

urls.py
from django.conf import settings
from django.conf.urls.defaults import patterns, include, url
from django.views.generic.simple import direct_to_template

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover ( )

urlpatterns = patterns ('',
    # url(r'^hocemtenis/', include('hocemtenis.foo.urls')),

    url (r'^$', 'ht.views.home', name='home'),
    url (r'^tos/$',
         direct_to_template,
         {'template': 'terms_of_service.html'},
         name='terms_of_service'),
    url (r'^wiki/', include ('wiki.urls')),
    url (r'^accounts/', include ('accounts.urls')),
    url (r'^clubs/', include ('clubs.urls')),
    url (r'^players/', include ('players.urls')),
    url (r'^reservations/', include ('reservations.urls')),
    url (r'^ranking/', include ('ranking.urls')),
    url (r'^user_messages/', include ('user_messages.urls')),
    url (r'^comments/', include ('comments.urls')),
    url (r'^activity/', include ('actstream.urls')),
    
    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
)

#
# Serve uploaded files only during development
#
if settings.DEBUG:
    urlpatterns += patterns ('',
        url (r'^media/(?P<path>.*)$',
             'django.views.static.serve',
             {'document_root': '%s/' % settings.MEDIA_ROOT,}),
   )

clubs/models.py
from django.db import models
from django.dispatch import receiver
from django.db.models import Count, Max
from django.core.exceptions import ValidationError
from django.db.models.signals import post_save, pre_delete
from django.utils.translation import ugettext
from django.utils.translation import ugettext_lazy as _

from clubs.managers import CourtManager, CourtSetupManager, VacancyManager
from accounts.models import ClubProfile



class CourtSetup (models.Model):
    """
    Enables different court configurations per club.-
    """
    name = models.CharField (max_length=100)
    club = models.ForeignKey (ClubProfile)
    is_active = models.BooleanField (default=False)
    objects = CourtSetupManager ( )

    def clean (self):
        """
        Only one court setup per club should be active.-
        """
        count = CourtSetup.objects.filter (club=self.club) \
                                  .filter (is_active=True)
        count = count.exclude (id=self.id) if self.id else count
        count = count.aggregate (Count ('id'))
        if (count['id__count'] > 0) and (self.is_active):
            raise ValidationError (_('Only one court setup may be active at once'))
    
    def __unicode__ (self):
        return self.name
    


@receiver (post_save, sender=ClubProfile)
def create_courtsetup (sender, instance, created, raw, **kwargs):
    """
    Callback function used whenever a new club profile is created.
    It creates a default court setup.-
    """
    #
    # Make sure a new club profile has been created by hand
    # (i.e. without fixtures)
    #
    if created and not raw:
        cs = CourtSetup.objects.create (name=ugettext('Default'),
                                        club=instance,
                                        is_active=True)
        cs.save ( )
        
        
            
class Court (models.Model):
    """
    A club's tennis court that is available for reservation.-
    """
    SURFACES = (('CL', _('Clay')),
                ('CE', _('Cement')),
                ('GR', _('Grass')),
                ('RU', _('Rubber')),
                ('CA', _('Carpet')))
    
    court_setup = models.ForeignKey (CourtSetup)
    number = models.IntegerField ( )
    indoor = models.BooleanField (default=False)
    light = models.BooleanField (default=True)
    surface = models.CharField (max_length=2,
                                choices=SURFACES,
                                default='CL')
    single_only = models.BooleanField (default=False)
    is_available = models.BooleanField (default=True)
    objects = CourtManager ( )
   
    class Meta:
        #
        # Don't allow a club to have repeated 
        # court numbers within an active setup
        # 
        unique_together = ('court_setup', 'number')
    
    def get_club (self):
        """
        Returns the club of this court.-
        """
        return self.court_setup.club
    
    def __unicode__ (self):
        return str (self.number)
 

 
@receiver (post_save, sender=CourtSetup)
def create_court (sender, instance, created, raw, **kwargs):
    """
    Callback function used whenever a new court setup is created.
    It creates one default court.-
    """
    #
    # Make sure a new court setup has been created by hand
    # (i.e. without fixtures)
    #
    if created and not raw:
        #
        # ... and that there are no courts yet
        #
        if Court.objects.get_count (instance) < 1:
            next_num = Court.objects.filter (court_setup=instance) \
                                    .aggregate (Max ('number'))
            if next_num['number__max']:
                next_num = next_num['number__max'] + 1
            else:
                next_num = 1
            c = Court.objects.create (court_setup=instance,
                                      number=next_num)
            c.save ( )



class Vacancy (models.Model):
    """
    Defines when and for how much a court is available for reservation.-
    """
    DAYS=((1, _('Monday')),
          (2, _('Tuesday')),
          (3, _('Wednesday')),
          (4, _('Thursday')),
          (5, _('Friday')),
          (6, _('Saturday')),
          (7, _('Sunday')))
    HOURS=((7, '7:00'),
           (8, '8:00'),
           (9, '9:00'),
           (10, '10:00'),
           (11, '11:00'),
           (12, '12:00'),
           (13, '13:00'),
           (14, '14:00'),
           (15, '15:00'),
           (16, '16:00'),
           (17, '17:00'),
           (18, '18:00'),
           (19, '19:00'),
           (20, '20:00'),
           (21, '21:00'),
           (22, '22:00'),
           (23, '23:00'),
           (24, '24:00'))
   
    court = models.ForeignKey (Court)
    day_of_week = models.IntegerField (choices=DAYS,
                                       default=1)
    available_from = models.IntegerField (choices=HOURS,
                                          default=8)
    available_to = models.IntegerField (choices=HOURS,
                                        default=9)
    price = models.DecimalField (max_digits=5,
                                 decimal_places=2,
                                 null=True,
                                 blank=True)
    objects = VacancyManager ( )
    
    class Meta:
        #
        # Don't allow court vacancies to overlap
        # 
        unique_together = ('court',
                           'day_of_week',
                           'available_from', 
                           'available_to')
        
    def clean (self):
        """
        Vacancy terms should be exactly one hour long.-
        """
        if (self.available_to - self.available_from) != 1:
            raise ValidationError (_('Vacancy terms should be one hour long'))
        
    def __unicode__ (self):
        return "%s, %s %s %s %s" % (self.get_day_of_week_display ( ),
                                    _('from'),
                                    self.available_from,
                                    _('to'),
                                    self.available_to)



@receiver (post_save, sender=Court)
def create_court_vacancy_terms (sender, instance, created, raw, **kwargs):
    """
    Callback function used whenever a new court is created.
    It creates all possible Vacancy terms for it.-
    """
    from ht_utils.models import insert_many
    #
    # Make sure a new court has been created by hand
    # (i.e. without fixtures)
    #
    if created and not raw:
        bulk = []
        days = [k for k,e in Vacancy.DAYS]
        hours = [k for k,e in Vacancy.HOURS]
        for d in days:
            for h in hours[:-1]:
                v = Vacancy (court=instance,
                             day_of_week=d,
                             available_from=h,
                             available_to=h+1,
                             price=None)
                bulk.append (v)
        insert_many (bulk)
 
 

@receiver(pre_delete, sender=Court)
def delete_associated_vacancy_terms (sender, instance, **kwargs):
    """
    Callback function used whenever a court is to be
    deleted. It deletes the associated Vacancy terms.-
    """
    #
    # Delete all Vacancy terms associated with this Court
    #
    Vacancy.objects.filter (court=instance).delete ( )

clubs/forms.py
from django import forms

from clubs.models import CourtSetup, Court
from accounts.models import ClubProfile



class EditCourtSetupForm (forms.ModelForm):
    """
    A form to add/change a court setup.-
    """
    club = forms.ModelChoiceField (queryset=ClubProfile.objects.all ( ),
                                   widget=forms.widgets.HiddenInput ( )) 
    class Meta:
        model = CourtSetup
       
        
class EditCourtPropertiesForm (forms.ModelForm):
    """
    A form to edit the court properties (e.g. surface, light, ...).-
    """
    court_setup = forms.ModelChoiceField (queryset=CourtSetup.objects.all ( ),
                                          widget=forms.widgets.HiddenInput ( ))
    class Meta:
        model = Court
        

templates/reservations/club_edit.html
{% extends "base.html" %}
{% load i18n %}
{% load url from future %}

{% block user_content %}

    <h1>
        {% blocktrans with num=form.instance.vacancy.court.number %}
            Reservation on court {{ num }}
        {% endblocktrans %}
    </h1>
    
	{% if form.errors %}
   	    {{ form.non_field_errors }}
	{% endif %}
	
    <div id="form">	
		<script>
			$(function ( )
			{
				toggleRepeat ( );
				$(":input[name=repeat]").click (function ( ) {
					toggleRepeat ( );
				});
				$("#id_repeat_until").datepicker ( );
			});
		    function toggleRepeat ( )
		    {
				chk = $(":input[type=checkbox][name=repeat]");
				cont = $(":input[type=text][name=repeat_until]").parent ("div");
				if (chk.is (':checked'))
				{
				    cont.css ("display", "block");
				}
		        else
		        {
		            cont.css ("display", "none");
		        }
		    }
            function cancelReservation ( )
            {
                $("form")[0].action="{% url 'reservations.views.club_view' %}";
                $("form")[0].submit ( );
                return;
            }
		</script>
		
		<form method="post" action="{% url 'reservations.views.club_edit' form.instance.vacancy.id ordinal_date %}">
			{% csrf_token %}
		    
		    <div id="form_elem">
			    <label for="id_for_date">{% trans 'Date' %}</label>
			    {{ form.for_date }}
			    {{ form.for_date.errors }}
	        </div>
		    	
		    <div id="form_elem">
		        <label for="id_from">{% trans 'From' %}</label>
		        {{ form.instance.vacancy.get_available_from_display }}
	        </div>
	        
		    <div id="form_elem">
		        <label for="id_to">{% trans 'To' %}</label>
		        {{ form.instance.vacancy.get_available_to_display }}
	        </div>
	        
		    <div id="form_elem">
		        <label for="id_description">{% trans 'Description' %}</label>
		        {{ form.description }}
			    {{ form.description.errors }}
	        </div>
	      
		    <div id="form_elem">
		        <label for="id_repeat">{% trans 'Repeat weekly?' %}</label>
		        {{ form.repeat }}
			    {{ form.repeat.errors }}
	        </div>
	        
		    <div id="form_elem">
		        <label for="id_repeat_until">{% trans 'until date' %}</label>
		        {{ form.repeat_until }}
			    {{ form.repeat_until.errors }}
	        </div>
	        
	       	{{ form.pk }} 
	        {{ form.created_on }}
	        {{ form.type }}
	        {{ form.user }}
	        {{ form.vacancy }}
	        
	        <div id="form_action"> 
			    <input type="submit" value="{% trans 'Save' %}" class="button"/>
			</div>
	        <div id="form_action">
                {% if form.instance.id %}
    	            <a href="{% url 'reservations.views.cancel' form.instance.id %}" class="button">
                {% else %}
    	            <a href="#" class="button" onclick="cancelReservation();">
                {% endif %}
	            {% trans 'Cancel reservation' %}</a>
			</div>
		</form>
	</div>
    	
{% endblock %}

templates/reservations/club_view.html
{% extends "base.html" %}
{% load url from future %}
{% load i18n %}


{% block user_content %}
	
	<div id="court_setup">
    	<h2>{{ court_setup.name|capfirst }}</h2>
    
		{% if form.errors %}
    	    {{ form.non_field_errors }}
		{% endif %}
		
    	<div id="form">
	    	<form method="post" action="#">
	    		{% csrf_token %}
			    
			    <div id="form_elem">
				    <label for="id_for_date">{% trans 'Date' %}</label>
				    {{ form.for_date }}
				    {{ form.for_date.errors }}
		        </div>
		       
		       	<input type="hidden" name="today_date" value="{{ today_date }}"/>
		       	<input type="hidden" name="prev_date" value="{{ prev_date }}"/>
		       	<input type="hidden" name="next_date" value="{{ next_date }}"/>
		       
		        <div id="form_action">
				    <input type="submit" value="{% trans 'Show' %}" class="button"/>
				</div>
		        <div id="form_action">
		       		<input type="button" value="{% trans 'Today' %}" class="button" onclick="javascript:goDay();"/> 
				</div>
	    	</form>
	    </div>
	    
	    <div id="day_shorcuts">
		    <article>
		        <header>
		            <script>
						$(function ( ) 
						{
		                    $.blockUI ({ 
		                        message: "{% trans 'Loading ...' %}",
		                        css: { 
		                            border: 'none', 
		                            padding: '15px', 
		                            backgroundColor: '#000', 
		                            opacity: .5, 
		                            color: '#fff'
		                        }
		                    });
		                    loadData ( );
							$("#id_for_date").datepicker ({
								onSelect: function (dateText, inst) 
								 		  {
										      document.forms[0].submit ( );
										  }
							});
						});
						function loadData ( )
						{
							$.ajax ({    url: '{% url "reservations.views.club_view" %}',
										type: 'POST',
										data: {'for_date': $("#id_for_date").val ( ), 
											   'csrfmiddlewaretoken': $('input[name="csrfmiddlewaretoken"]').val ( )},
									   cache: false,
									 success: function (data)
									          {
										          $('#court_setup').append (data);
										          $.unblockUI ( );
										      },
									});
							return;
						};
		                function goDay (opt)
		                {
		                	switch (opt)
		                	{
		                		case -1: 
		                			new_d = $('input[name="prev_date"]').val ( );
		                			break;
		                		case 1:
		                			new_d = $('input[name="next_date"]').val ( );
		                			break;
		                		default:
		                			new_d = $('input[name="today_date"]').val ( );
		                	}
		                	document.forms[0].for_date.value = new_d;
		                	document.forms[0].submit ( );
		                	return;
		                };
		            </script>
		        </header>
		        <div id="day_shortcuts_left">
				    <a href="javascript:goDay(-1);" class="small_button"><< {% trans 'Previous week' %}</a>
			    </div>
		        <div id="day_shortcuts_right">
				    <a href="javascript:goDay(1);" class="small_button">{% trans 'Next week' %} >></a>
			    </div>
		    </article>
		</div>
	</div>
	
{% endblock %}

templates/reservations/club_view_table.html
{% load reservation_tags %}

<table class="reservation">
    <caption>
           {{ form.for_date.value|date:"l, j. F Y"|capfirst }}
	</caption>
       <thead>
           <tr>
               <th scope="col">&nbsp;</th>
               {% for d in week_date_list %}
                  <th scope="col">{{ d|date:"D, d.m." }}</th>
               {% endfor %}
           </tr>
       </thead>
       <tbody>
           {% for h, hour in hour_list %}
				<tr {% if forloop.counter|divisibleby:2 %}class="odd"{% endif %}>
					<th scope="row">
						{{ hour }}
	                </th>
	                {% for d in week_date_list %}
	                	{% reservations_per_day terms d h %}
	                {% endfor %}
	            </tr>
	       {% endfor %}
       </tbody>
       <tfoot>
         	<tr>
               <th scope="col">&nbsp;</th>
               {% for d in week_date_list %}
                  <th scope="col">{{ d|date:"D, d.m." }}</th>
               {% endfor %}
            </tr>
       </tfoot>
</table>

templates/reservations/player_edit.html
{% extends "base.html" %}
{% load i18n %}
{% load url from future %}

{% block user_content %}
	<h1>{% trans 'Confirm reservation' %}</h1>
	
	{% if form.errors %}
   	    {{ form.non_field_errors }}
	{% endif %}
	
    <div id="form">	
		<form method="post" action="{% url 'reservations.views.player_edit' form.instance.vacancy.id ordinal_date %}">
			{% csrf_token %}
		    
		    <div id="form_elem">
			    <label for="id_for_date">{% trans 'Date' %}</label>
			    {{ form.for_date }}
			    {{ form.for_date.errors }}
	        </div>
		    	
		    <div id="form_elem">
		        <label for="id_from">{% trans 'From' %}</label>
		        {{ form.instance.vacancy.get_available_from_display }}
	        </div>
	        
		    <div id="form_elem">
		        <label for="id_to">{% trans 'To' %}</label>
		        {{ form.instance.vacancy.get_available_to_display }}
	        </div>
	        
		    <div id="form_elem">
		        <label for="id_club">{% trans 'Club' %}</label>
		        {{ form.instance.vacancy.court.court_setup.club.user.first_name }}
		        {{ form.instance.vacancy.court.court_setup.club.user.last_name }}
	        </div>
	        
		    <div id="form_elem">
		        <label for="id_court">{% trans 'Court' %}</label>
		        {{ form.instance.vacancy.court.number }}
	        </div>
	        
		    <span style="display:none;">
		        {{ form.description }}
		        {{ form.repeat }}
		        {{ form.repeat_until }}
	        </span>
	       
	       	{{ form.pk }} 
	        {{ form.created_on }}
	        {{ form.type }}
	        {{ form.user }}
	        {{ form.vacancy }}
	        
	        <div id="form_action"> 
			    <input type="submit" value="{% trans 'Confirm' %}" class="button"/>
			</div>
		</form>
	</div>
    	
{% endblock %}

templates/reservations/reservation_count_per_club.html
{% load i18n %}
{% load url from future %}

<article>
	<header>
	</header>
    <ul>
        <li>
            <a href='#'>{% trans 'Today' %}</a>
            {{ today_count }}
        </li>
        <li>
            <a href='#'>{% trans 'Tomorrow' %}</a>
            {{ tomorrow_count }}
        </li>
        <li>
            <a href='#'>{% trans 'Next week' %}</a>
            {{ week_count }}
        </li>
    </ul>
</article>

templates/reservations/reservations_per_day.html
{% load i18n %}
{% load url from future %}

<td>
	{% for vacancy,reservation in term_list %}
		<a href="{% url 'reservations.views.club_edit' vacancy.id for_date.toordinal %}" 
			{% if reservation %}
	            class="court_button booked_court_button_{{ vacancy.court.number }}" 
				title="{{ reservation.description }}">
			{% else %}
					class="court_button free_court_button_{{ vacancy.court.number }}"
					title="{% trans 'Free' %}">
			{% endif %}
		</a>
	{% endfor %}
</td>

templates/reservations/search.html
{% extends "base.html" %}
{% load i18n %}
{% load url from future %}

{% block anonymous_content %}

    <div id="form">	
		<form method="post" action="{% url 'reservations.views.search' %}">
			{% csrf_token %}
			
			{% if form.errors %}
	    	    {{ form.non_field_errors }}
			{% endif %}
		    
		    <div id="form_elem">
			    {{ form.location.errors }}
			    <label for="id_location">{% trans 'Near city' %}</label>
			    {{ form.location }}
	        </div>
		    	
		    <div id="form_elem">
			    {{ form.for_date.errors }}
		        <label for="id_for_date">{% trans 'Date and Time' %}</label>
		        {{ form.for_date }}
	        </div>
	        
		    <div id="form_elem">
			    {{ form.for_time.errors }}
		        <label for="id_for_time">&nbsp;</label>
		        {{ form.for_time }}
	        </div>
	        
		    <div id="form_elem">
			    {{ form.hours.errors }}
		        <label for="id_hours">{% trans 'for' %}</label>
		        {{ form.hours }}
	        </div>
	        
	        <div id="form_action"> 
			    <input type="submit" value="{% trans 'Search' %}" class="button"/>
			</div>
		</form>
	</div>

    {% block search_results %}
        <!-- 
		<h2>{% trans 'Featured clubs' %}</h2>
		<br/><br/><br/><br/><br/>
	
	    <h2>{% trans 'Fast reservation' %}</h2>
		<br/><br/><br/><br/><br/>
        -->
	{% endblock %}
    	
{% endblock %}

templates/reservations/transfer_or_delete.html
{% extends "base.html" %}
{% load i18n %}
{% load url from future %}

{% block user_content %}
	<h1>{% trans 'Transfer or delete reservations?' %}</h1>
    
    <br/>	
	<h3>{% trans 'The system has found that there are booked courts over the object you have selected.' %}</h3>
	<h3>{% trans 'Please indicate, what should we do with them.' %}</h3>
	<br/>
	
	{% if form.errors %}
   	    {{ form.non_field_errors }}
	{% endif %}
	
    <div id="form">	
		<form method="post" action="#">
			{% csrf_token %}
		    
		    <div id="form_elem">
			    <label for="id_user_choice">{% trans 'Select one of these actions:' %}</label>
			    {{ form.user_choice }}
			    {{ form.user_choice.errors }}
	        </div>
	        
		    <div id="form_elem">
			    <label for="id_transfer_to">{% trans 'Transfer to:' %}</label>
			    {{ form.transfer_to }}
			    {{ form.transfer_to.errors }}
	        </div>
	        
	        <div id="form_action"> 
			    <input type="submit" value="{% trans 'Confirm' %}" class="button"/>
			</div>
	        <div id="form_action"> 
			    <input type="button" value="{% trans 'Discard' %}" class="button"/>
			</div>
		</form>
	</div>
	
	<table class="reservation">
		<caption>
			{% trans 'Reservations found' %}
		</caption>
		<thead>
			<tr>
				<th scope="col">&nbsp;</th>
				<th scope="col">{% trans 'Date' %}</th>
                <th scope="col">{% trans 'From' %}</th>
                <th scope="col">{% trans 'To' %}</th>
                <th scope="col">{% trans 'Court' %}</th>
                <th scope="col">{% trans 'Description' %}</th>
                <th scope="col">{% trans 'Repetition?' %}</th>
            </tr>
		</thead>
		<tbody>
			{% for res in res_list %}
				<tr>
					<td>&nbsp;</td>
					<td>{{ res.for_date|date:"SHORT_DATE_FORMAT" }}</td>
					<td>{{ res.vacancy.get_available_from_display }}</td>
					<td>{{ res.vacancy.get_available_to_display }}</td>
					<td>{{ res.vacancy.court }}</td>
					<td>{{ res.description }}</td>
					<td>
						{% if res.repeat_series %}
							{% trans 'Yes' %}
						{% else %}
							{% trans 'No' %}
						{% endif %}
					</td>
				</tr>
			{% endfor %}
		</tbody>
	</table>
    	
{% endblock %}